"""
PySpark Model Definition and Cross-Validation Utility.

This module provides the ModelDefinePipelineSpark class, which encapsulates the
process of defining a PySpark ML Pipeline, setting up a hyperparameter search
grid using ParamGridBuilder, and performing cross-validation (CrossValidator)
on the pipeline. It is designed to streamline the training and evaluation
of regression models in a Spark environment.

Classes
-------
ModelDefinePipelineSpark
    A utility class to wrap a PySpark ML model and its required preprocessing
    steps (VectorAssembler) within a CrossValidator for hyperparameter tuning.
"""

# Import necessary modules
from typing import Any, cast

from pyspark.ml import Estimator, Pipeline, PipelineModel
from pyspark.ml.evaluation import RegressionEvaluator
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.tuning import CrossValidator, CrossValidatorModel, ParamGridBuilder
from pyspark.sql import DataFrame

# Utility functions
from src.utils import evaluate_model, save_model


class ModelDefinePipelineSpark:
    """
    A utility class to define a PySpark ML training pipeline with Cross-Validation setup.

    The class handles:
    1. Assembling input columns into a single "features" vector (`VectorAssembler`).
    2. Creating the pipeline (Assembler -> Model).
    3. Defining the parameter grid (`ParamGridBuilder`).
    4. Setting up the cross-validator (`CrossValidator`) with the primary evaluator.

    Parameters
    ----------
    name : str
        The name of the model/experiment (used for logging/saving).
    model : pyspark.ml.Estimator
        The PySpark ML estimator (e.g., GBTRegressor, RandomForestRegressor) to be tuned.
    input_columns : list of str
        The list of columns to be assembled into the "features" vector.
    label_column : str
        The name of the target/dependent column.
    evaluators : list of str
        A list of evaluation metrics to calculate (e.g., ["rmse", "r2"]). The first metric
        in the list is used as the primary metric for the CrossValidator.
    param_dict : dict of {str: list of object}
        A dictionary where keys are parameter names (str) of the Estimator and values
        are lists of parameter values to be searched in the grid.
    num_folds : int, optional
        The number of folds to use for cross-validation. Default is 3.

    Attributes
    ----------
    name : str
        The model/experiment name.
    model : pyspark.ml.Estimator
        The base ML estimator instance.
    input_columns : list of str
        List of feature columns.
    label_column : str
        Name of the label column.
    assembler : pyspark.ml.feature.VectorAssembler
        Transformer responsible for creating the "features" vector.
    evaluators : list of str
        List of metric names to evaluate.
    evaluators_dict : dict of {str: pyspark.ml.evaluation.RegressionEvaluator}
        Dictionary mapping metric names to instantiated PySpark evaluators.
    param_dict : dict
        The parameter search space dictionary provided during initialization.
    param_grid : list of dict
        The final list of parameter maps generated by ParamGridBuilder.
    num_folds : int
        The number of cross-validation folds.
    pipeline : pyspark.ml.Pipeline
        The pipeline object (VectorAssembler -> Model) used as the estimator for CrossValidator.
    cv : pyspark.ml.tuning.CrossValidator
        The cross-validator object configured for hyperparameter tuning.
    cv_model : pyspark.ml.tuning.CrossValidatorModel or None
        The fitted model (best model from cross-validation). Populated after calling `fit()`.
    """

    def __init__(
        self,
        name: str,
        model: Estimator,
        input_columns: list[str],
        label_column: str,
        evaluators: list[str],
        param_dict: dict[str, list[object]],
        num_folds: int = 3,
    ) -> None:
        """
        Initializes the model definition pipeline, assembling all components
        (assembler, evaluator, parameter grid, and cross-validator).

        Parameters
        ----------
        name : str
            The name of the model/experiment.
        model : pyspark.ml.Estimator
            The PySpark ML estimator to be tuned.
        input_columns : list of str
            The list of columns to be assembled into the "features" vector.
        label_column : str
            The name of the target/dependent column.
        evaluators : list of str
            A list of evaluation metrics to calculate (e.g., ["rmse", "r2"]).
        param_dict : dict of {str: list of object}
            A dictionary defining the parameter search space for the model.
        num_folds : int, optional
            The number of folds to use for cross-validation. Default is 3.
        """

        self.name = name
        self.model = model

        self.input_columns = input_columns
        self.label_column = label_column

        self.assembler = VectorAssembler(
            inputCols=self.input_columns,
            outputCol="features",
        )

        self.evaluators = evaluators
        self.evaluators_dict = self.create_evaluator_dict()

        self.param_dict = param_dict

        builder = ParamGridBuilder()

        for param_name, values in self.param_dict.items():
            # get the Param object from the estimator
            param = getattr(self.model, param_name)
            builder = builder.addGrid(param, values)

        self.param_grid = builder.build()

        self.num_folds = num_folds

        self.pipeline = Pipeline(stages=[self.assembler, self.model])
        self.cv = CrossValidator(
            estimator=self.pipeline,
            estimatorParamMaps=self.param_grid,
            evaluator=cast(RegressionEvaluator, list(self.evaluators_dict.values())[0]),
            numFolds=self.num_folds,
            parallelism=1,
        )

    def create_evaluator_dict(self) -> dict[str, RegressionEvaluator]:
        """
        Creates a dictionary of PySpark RegressionEvaluator instances based on
        the requested metrics (rmse, mse, r2, mae, var).

        Returns
        -------
        dict of {str: pyspark.ml.evaluation.RegressionEvaluator}
            A dictionary mapping metric names to their corresponding configured evaluators.
        """

        allowed_metrics = ["rmse", "mse", "r2", "mae", "var"]

        evaluator_dict: dict[str, RegressionEvaluator] = {}
        for metric in self.evaluators:
            if metric not in allowed_metrics:
                continue

            evaluator = RegressionEvaluator(
                labelCol=self.label_column,
                predictionCol="prediction",
                metricName=metric,  # type: ignore
            )

            evaluator_dict[metric] = evaluator

        return evaluator_dict

    def fit(
        self,
        X: DataFrame,
        save_name: str | None = None,
    ) -> CrossValidatorModel:
        """
        Fits the CrossValidator to the input data and optionally saves the resulting
        best model (CrossValidatorModel).

        Parameters
        ----------
        X : pyspark.sql.DataFrame
            The input training DataFrame.
        save_name : str or None, optional
            The name under which to save the fitted CrossValidatorModel using the
            `save_model` utility function. If None, the model is not saved. Default is None.

        Returns
        -------
        pyspark.ml.tuning.CrossValidatorModel
            The fitted model, containing the best performing pipeline model found
            during cross-validation.
        """

        self.cv_model = self.cv.fit(X)

        if save_name is not None:
            save_model(self.cv_model, save_name)

        return self.cv_model

    def evaluate(self, test_df: DataFrame) -> dict[str, float]:
        """
        Evaluates the fitted CrossValidatorModel (best model) on the test DataFrame
        using all configured evaluators.

        The evaluation utilizes the external `evaluate_model` utility.

        Parameters
        ----------
        test_df : pyspark.sql.DataFrame
            The DataFrame used for testing the fitted model.

        Returns
        -------
        dict of {str: float}
            A dictionary mapping each metric name to its calculated score.
        """

        score_dict = evaluate_model(
            name=self.name,
            model=self.cv_model,
            test_df=test_df,
            evaluators=self.evaluators_dict,
        )
        return score_dict

    def set_model(self, cv_model: CrossValidatorModel) -> None:
        """
        Manually sets the fitted CrossValidatorModel instance.

        This is typically used to load a previously saved model for evaluation
        or prediction without re-running the `fit` method.

        Parameters
        ----------
        cv_model : pyspark.ml.tuning.CrossValidatorModel
            The pre-fitted CrossValidatorModel to be set.
        """

        self.cv_model = cv_model
        return None

    def get_pipeline(self) -> Pipeline:
        """
        Retrieves the unfitted Pipeline object defined within the class.

        Returns
        -------
        pyspark.ml.Pipeline
            The defined pipeline (VectorAssembler -> Model).
        """

        return self.pipeline

    def get_cross_validator(self) -> CrossValidator:
        """
        Retrieves the unfitted CrossValidator object defined within the class.

        Returns
        -------
        pyspark.ml.tuning.CrossValidator
            The defined cross-validator setup.
        """

        return self.cv

    def get_best_params(self) -> dict[str, Any]:
        """
        Extracts and prints the parameters that yielded the best model during cross-validation.

        Returns
        -------
        dict of {str: object}
            A dictionary containing the parameter names and their best-performing values.

        Raises
        ------
        AttributeError
            If the `fit()` method has not been called and `self.cv_model` is None.
        """

        best_pipeline = cast(PipelineModel, self.cv_model.bestModel)
        best_model = best_pipeline.stages[-1]

        param_map = best_model.extractParamMap()

        for p, v in param_map.items():
            if p.name in self.param_dict:
                print(p.name, "=", v)

        return {p.name: v for p, v in param_map.items() if p.name in self.param_dict}
